### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hdbreaker** [projectdiscovery/katana#380] opened 2023-03-26 17:00 UTC
When crawling a site using katana:
katana -u {url} -hl -nos -jc -aff -kf all

In some point failed with error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x4c0a3d7]

goroutine 15701 [running]:
github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).navigateRequest(0xc0005581c0, {0x55d73c8?, 0xc000558200?}, 0xc00054ba70?, 0xc00054ea20, 0xc000572fc0?, 0xc000817e00, {0xc0003d0207, 0x17})
	/Users/hdbreaker/go/pkg/mod/github.com/projectdiscovery/katana@v1.0.0/pkg/engine/hybrid/crawl.go:153 +0xc77
github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).Crawl.func2()
	/Users/hdbreaker/go/pkg/mod/github.com/projectdiscovery/katana@v1.0.0/pkg/engine/hybrid/hybrid.go:242 +0x165
created by github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).Crawl
	/Users/hdbreaker/go/pkg/mod/github.com/projectdiscovery/katana@v1.0.0/pkg/engine/hybrid/hybrid.go:232 +0xda5
```

The error is related to headless hybrid crawler.

**Comment by gister9000** [comment] 2023-04-25 11:04
+1

Happens to me to all the time:

```
[Katana] Running katana -list /home/ubuntu/appsec/appsecintel/projects/tamg/katana_services.txt -crawl-scope /home/ubuntu/appsec/appsecintel/projects/tamg/katana_services.txt -store-response -display-out-scope -known-files all -js-crawl -headless -system-chrome -headless-options -rate-limit 1000 -parallelism 10 -concurrency 10 -timeout 15 -max-response-size 20971520 -crawl-duration 86400 --crawl-out-scope /home/ubuntu/appsec/appsecintel/projects/tamg/katana_domain_blacklist.txt > /home/ubuntu/appsec/appsecintel/projects/tamg/katana_links.txt
[Katana] 
[Katana]    __        __                
[Katana]   / /_____ _/ /____ ____  ___ _
[Katana]  /  '_/ _  / __/ _  / _ \/ _  /
[Katana] /_/\_\\_,_/\__/\_,_/_//_/\_,_/							 
[Katana] 
[Katana] 		projectdiscovery.io
[Katana] 
[Katana] [INF] Current katana version v1.0.0 (outdated)
[Katana] panic: runtime error: invalid memory address or nil pointer dereference
[Katana] [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x101b597]
[Katana] 
[Katana] goroutine 34256 [running]:
[Katana] github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).navigateRequest(0xc0073c6000, {0x413e45?, 0x0?}, 0x97?, 0xc014b64630, 0x1?, 0xc006301f40, {0xc0005884b7, 0x1c})
[Katana] 	/home/runner/work/katana/katana/pkg/engine/hybrid/crawl.go:153 +0xc77
[Katana] github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).Crawl.func2()
[Katana] 	/home/runner/work/katana/katana/pkg/engine/hybrid/hybrid.go:242 +0x165
[Katana] created by github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).Crawl
[Katana] 	/home/runner/work/katana/katana/pkg/engine/hybrid/hybrid.go:232 +0xda5
```

**Comment by Hayashi2026** [comment] 2023-04-26 04:00
happens to me all the time as well. When using headless mode, I encounter this issue with versions 1.0.1 and 1.0.0. It appears that the issue is with the versions after 0.0.3 since switching to version 0.0.3 resolves the problem and works without any issues.

**Comment by RamanaReddy0M** [comment] 2023-05-04 13:04
@hdbreaker @gister9000, Can you please try with katana latest version(1.0.1)?
I am not able to reproduce the issue with the latest version.

Let me know if the problem still persists, thank you.

**Comment by nbxiglk0** [comment] 2023-05-16 07:30
Still persists with 1.0.1.  
Version: 1.0.1  
![image](https://github.com/projectdiscovery/katana/assets/24366795/78be70e2-32e0-4544-810d-5e56ee2c5e44)  
![image](https://github.com/projectdiscovery/katana/assets/24366795/c8b29671-22ce-47c0-a67d-ca9728d67f06)

**Comment by ehsandeep** [comment] 2023-05-16 18:53
@Hayashi2026 @hdbreaker @nbxiglk0 @gister9000 should be fixed in dev branch with https://github.com/projectdiscovery/katana/pull/436

**Comment by ehsandeep** [comment] 2023-06-12 22:43
now added in latest release - https://github.com/projectdiscovery/katana/releases/tag/v1.0.2

**Closed by ehsandeep** 2023-06-12 22:43 UTC
Labels: Status: Completed, Type: Bug
