### ISSUE TITLE
remote error: tls: user canceled with burp proxy

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/katana#170] opened 2022-11-11 19:21 UTC
### Discussed in https://github.com/projectdiscovery/katana/discussions/165

<div type='discussions-op-text'>

<sup>Originally posted by **tequreq** November 11, 2022</sup>
I used 0.0.1 version of katana,

`katana -proxy http://127.0.0.1:8080 -u https://site.com -d 5 -jc  -v`

output : 
`[WRN] Could not request seed URL: remote error: tls: user canceled`

But trying with 'kf' param that requesting correctly. 

`./katana -proxy http://127.0.0.1:8080 -u https://site.com -d 5 -jc  -kf all -v`

output : 

```
[file] https://site.com/
[file] https://site.com/robots.txt
[file] https://site.com/m/
[file] https://site.com/mobile/
[file] https://site.com/ara?
[file] https://site.com/ara/
[file] https://site.com/admin/
[file] https://site.com/api/
[file] https://site.com/articles/
[file] https://site.com/notp/
[file] https://site.com/dev
[file] https://site.com/mesaj/
[WRN] Could not parse known files for https://site.com: could not parse sitemap: could not decode xml: XML syntax error on line 2: attribute name without = in element
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[header] https://site.com/ara/haber
[WRN] Could not request seed URL: remote error: tls: user canceled
[header] https://site.com/ara/ara/haber
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
[WRN] Could not request seed URL: remote error: tls: user canceled
```

**Comment by ehsandeep** [comment] 2022-11-11 19:23
We had a similar issue in httpx with burp that were fixed recently - https://github.com/projectdiscovery/httpx/pull/753

**Comment by Mzack9999** [comment] 2023-01-08 21:45
https://github.com/projectdiscovery/httpx/pull/753 isn't a proper fix but a recoverable error, which leads to being unable to read the response body, which is acceptable in httpx, doesn't meet the requirements of a crawler. The problem is between the go client attempting to connect with tls1.3 and burp proxy early-closing the connection (probably not supporting it properly). The problem happens only with burp proxy, so I don't know if enforcing tls1.2 for all proxies is a viable generic solution.

**Comment by tarunKoyalwar** [comment] 2023-01-20 16:53
@Mzack9999  , I think burpsuite interface url (http://burpsuite) is enabled by default . we can do a HTTP probe and check if proxy is burpsuite and then we can use tls 1.2 only while using burpsuite for now

**Closed** 2023-03-20 11:08 UTC
Labels: Priority: Low, Status: Completed, Type: Bug
