### ISSUE TITLE
It seems katana hang up somewhere

### ISSUE THREAD

**Issue by leveryd** [projectdiscovery/katana#416] opened 2023-04-21 02:30 UTC
### katana version:

v1.0.1
### Current Behavior:

The crawler task do not finish after 16h, it seems like hanging.

### Expected Behavior:

The crawler should not hang, at least, it should exit when the whole task run too long.

### Steps To Reproduce:

```
docker run -ti --privileged --rm projectdiscovery/katana:v1.0.1 -v -aff -u 'http://aipage.com:80' -system-chrome -headless
```

But i think this can not reproduce every time

**Comment by shizzgar** [comment] 2023-04-25 13:56
Have spotted same behavior

**Comment by mr-pmillz** [comment] 2023-05-15 19:32
I've also noticed that when running Katana as a Library, the output file gets created but no content is added to the output file.
Here's an example I was testing that produced no output.

```go
package recon

import (
	"fmt"
	"blah/blah/blahblah/v3/localio"
	"github.com/projectdiscovery/gologger"
	"github.com/projectdiscovery/katana/pkg/engine/standard"
	"github.com/projectdiscovery/katana/pkg/types"
	"net/url"
	"os"
	"regexp"
	"sync"
)

var nonAlphanumericRegex = regexp.MustCompile(`[^.a-zA-Z0-9 ]+`)

func clearString(str string) string {
	return nonAlphanumericRegex.ReplaceAllString(str, "-")
}

// runKatanaConcurrent ...
func runKatanaConcurrent(urlsFile string, opts *Options, workers int) error {
    // psuedo code from a private lib, ReadLines returns a slice of urls from a file containing line delimited urls...
	targetURLs, err := localio.ReadLines(urlsFile)
	if err != nil {
		return localio.LogError(err)
	}

	if err = os.MkdirAll(fmt.Sprintf("%s/katana", opts.Output), os.ModePerm); err != nil {
		return localio.LogError(err)
	}

	tasks := make(chan string, len(targetURLs))
	var wg sync.WaitGroup

	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func(num int) {
			defer wg.Done()
			for target := range tasks {
				if err := runKatanaNative(target, opts.Output, opts.UserAgent); err != nil {
					localio.LogWarningf("Error running Katana for URL: %s", target)
				}
			}
		}(i)
	}

	for _, targetURL := range targetURLs {
		tasks <- targetURL
	}
	close(tasks)
	wg.Wait()

	return nil
}

// runKatanaNative ...
func runKatanaNative(targetURL, outputDir, userAgent string) error {
	_, err := url.Parse(targetURL)
	if err != nil {
		localio.LogWarningf("URL invalid: %s", targetURL)
		return nil
	}
	options := &types.Options{
		URLs:              []string{targetURL},
		ExtensionFilter:   []string{"png", "css", "svg", "jpg"},
		MaxDepth:          3,               // Maximum depth to crawl
		BodyReadSize:      2 * 1024 * 1024, // Maximum response size to read
		Timeout:           10,
		CrawlDuration:     600,
		Concurrency:       10,
		Parallelism:       10,
		Strategy:          "depth-first", // Visit strategy (depth-first, breadth-first)
		FieldScope:        "rdn",         // Crawling Scope Field
		OutputFile:        fmt.Sprintf("%s/katana/katana-%s.txt", outputDir, clearString(targetURL)),
		KnownFiles:        "all",
		NoColors:          false,
		JSON:              false,
		Silent:            true,
		Verbose:           false,
		Version:           false,
		ScrapeJSResponses: true,
		CustomHeaders:     []string{fmt.Sprintf("User-Agent: %s", userAgent)},
		OnResult: func(result output.Result) { // Callback function to execute for result
			gologger.Info().Msg(result.Request.URL)
		},
		DisableUpdateCheck: false,
		IgnoreQueryParams:  false,
		Debug:              false,
	}
	crawlerOptions, err := types.NewCrawlerOptions(options)
	if err != nil {
		gologger.Fatal().Msg(err.Error())
	}
	defer crawlerOptions.Close()
	crawler, err := standard.New(crawlerOptions)
	if err != nil {
		return localio.LogError(err)
	}

	localio.Infof("Running Katana against URL: %s", targetURL)
	if err = crawler.Crawl(targetURL); err != nil {
		return localio.LogError(err)
	}

	err = crawler.Close()
	if err != nil {
		return localio.LogError(err)
	}
	return nil
}
```

Have tried multiple options but seems that the found links are never written to the output files and the processes hang / fail to terminate on the 5 minute / 600 second timeout.

![image](https://github.com/projectdiscovery/katana/assets/58376398/a28e1383-a907-4a93-b98d-000fcd186bce)

Is this information helpful?

When i run it via the CLI from go via exec.Command... it runs perfectly fine, but as a library, seems to be some issues or a hidden bug lurking in the katana code base somewhere 🤔 

Any who, awesome tool, am excited to migrate to using it natively as a package library.
Cheers 🍻

**Comment by iamnihal** [comment] 2023-12-17 18:32
I am facing the same issue as @mr-pmillz while using katana as a library. It stops instantly.

**Output:**
![image](https://github.com/projectdiscovery/katana/assets/37813784/92746011-39ec-4aec-8a2f-bccd280498ff)

**Comment by dogancanbakir** [comment] 2023-12-20 12:16
@leveryd,
@shizzgar,
Could you please try again using the latest version?

```console
$ docker run -ti --privileged --rm projectdiscovery/katana:v1.0.3 -aff -u 'http://aipage.com:80' -system-chrome -headless

   __        __
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/							

		projectdiscovery.io

[INF] Current katana version v1.0.3 (outdated)
[INF] Started headless crawling for => http://aipage.com:80
http://aipage.com/static/aipage/page/preview/client_f0c4772.js
http://aipage.com/static/aipage/pkg/lib_bac73d8.js
http://aipage.com/static/aipage/pkg/page_b0c1ef5.js
http://aipage.com/static/aipage/page/preview/'+t.link+'
http://aipage.com/static/aipage/pkg/'+(t?t.cover||i:i)+'
http://aipage.com/static/aipage/pkg/'+window.URL.createObjectURL(e)+'
http://aipage.com:80
http://aipage.com/static/aipage/pkg/%7B%7Bitem.cover%7D%7D
http://aipage.com/static/aipage/pkg/%27+%28t.portrait%7C%7C
http://aipage.com/static/aipage/pkg/'+a.agreeLink+'
http://aipage.com/openapi/captcha?raw=1&id='+e+'
http://aipage.com/openapi/captcha?raw=1&id=login
http://aipage.com/static/aipage/page/preview/client_8538d3b.css
http://aipage.com/static/aipage/pkg/page_659e841.css
http://aipage.com/static/aipage/page/login/login_04a46e7.css
http://aipage.com/preview/site/6636a3e0-30a2-4b4f-8acb-5af3ab527218/submit-xuqiu
http://aipage.com/submit-xuqiu
http://aipage.com/preview/site/6636a3e0-30a2-4b4f-8acb-5af3ab527218/6eebff8c-7c17-4d3d-a395-e10ba3d0c25b
http://aipage.com/preview/site/6636a3e0-30a2-4b4f-8acb-5af3ab527218/article-faq?cateId=e6226753-6f51-42ad-bd09-a99e59b5e7d7
http://aipage.com/login?redirectUrl=http%3A%2F%2Faipage.com%2Fsubmit-xuqiu
http://aipage.com/login?redirectUrl=http%3A%2F%2Faipage.com%2Fpreview%2Fsite%2F6636a3e0-30a2-4b4f-8acb-5af3ab527218%2Fsubmit-xuqiu
http://aipage.com/login?redirectUrl=http%3A%2F%2Faipage.com%2Fpreview%2Fsite%2F6636a3e0-30a2-4b4f-8acb-5af3ab527218%2F6eebff8c-7c17-4d3d-a395-e10ba3d0c25b
http://aipage.com/login?redirectUrl=http%3A%2F%2Faipage.com%2Fpreview%2Fsite%2F6636a3e0-30a2-4b4f-8acb-5af3ab527218%2Farticle-faq%3FcateId%3De6226753-6f51-42ad-bd09-a99e59b5e7d7
http://aipage.com/page-jiaocheng
http://aipage.com/preview/site/6636a3e0-30a2-4b4f-8acb-5af3ab527218/xinlingshou-site
http://aipage.com/login?redirectUrl=http%3A%2F%2Faipage.com%2Fpage-jiaocheng
http://aipage.com/page-dzdj8
http://aipage.com/login?redirectUrl=http%3A%2F%2Faipage.com%2Fpage-anli
http://aipage.com/page-anli
http://aipage.com/login?redirectUrl=http%3A%2F%2Faipage.com%2Fpreview%2Fsite%2F6636a3e0-30a2-4b4f-8acb-5af3ab527218%2Fxinlingshou-site
http://aipage.com/resources/sys/lib/jquery.simplePagination.js
http://aipage.com/resources/sys/lib/qrcode.min.js
http://aipage.com/resources/sys/lib/template-web.js
http://aipage.com/login?redirectUrl=http%3A%2F%2Faipage.com%2Fpage-zzdj8
http://aipage.com/login?redirectUrl=http%3A%2F%2Faipage.com%2Fpage-dzdj8
http://aipage.com/
http://aipage.com/page-zzdj8
http://aipage.com/template-market
```

**Comment by dogancanbakir** [comment] 2023-12-20 12:22
@iamnihal,
Could you please retry using this updated example? https://github.com/projectdiscovery/katana/pull/703/

**Comment by dogancanbakir** [comment] 2023-12-20 12:23
@mr-pmillz,
I believe this is an incomplete code snippet. Can you please share the complete example with me so I can reproduce the issue? Thanks!

**Comment by iamnihal** [comment] 2023-12-20 16:14
> @iamnihal, Could you please retry using this updated example? #703

It's working for me. Thanks a lot, @dogancanbakir 

I'm curious, how did you arrive at the solution? I attempted to include all the fields with default values earlier, but it didn't seem to work.

**Comment by dogancanbakir** [comment] 2023-12-21 09:15
@iamnihal, I only set the options that had a default value in CLI. For instance, I added the `FieldScope` option because it had a default value of "rdn", but I skipped the `Headless` option because it didn't have a default value. Also, variables declared without an explicit initial value are given their zero value automatically, so there's no need to set them again. I hope that clears things up for you! See: https://github.com/projectdiscovery/katana/blob/3558f38f8546f9ecc064c6c647fddd097c05bed7/cmd/katana/main.go#L78

**Comment by iamnihal** [comment] 2023-12-22 09:06
@dogancanbakir - This clears my doubt. Thank you for the detailed explanation. I truly appreciate it.

You've set the `Delay: 0`; the `Delay` field is of type `int`, and if it's not set explicitly, it will take the default value of 0. So, if we did not set it explicitly, the code would work fine (which it does).

This is what I understood. Let me know if I got it right!

**Comment by dogancanbakir** [comment] 2023-12-22 09:16
@iamnihal, Yes!

**Comment by dogancanbakir** [comment] 2023-12-27 09:37
Closing this. Feel free to reopen if the issue persists.

**Closed by dogancanbakir** 2023-12-27 09:37 UTC
Labels: Type: Bug, Investigation
