### ISSUE TITLE
Field option doesn't work with depth 1

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/katana#471] opened 2023-06-05 17:01 UTC
### katana version:
latest

### Current Behavior:
Field option doesn't work with `-d 1`

```console
echo https://www.mandiant.com/report-incident | katana -f email -d 1 -silent
```

### Expected Behavior:
Field option to work with `-d 1` based on requested page response.

```console
echo https://www.mandiant.com/report-incident | katana -f email -d 1 -silent

investigations@mandiant.com
investigations@mandiant.com
```

### Steps To Reproduce:
```
echo https://www.mandiant.com/report-incident | katana -f email
```

**Comment by dogancanbakir** [comment] 2024-03-29 09:48
I am unable to reproduce this issue. It may have been resolved at some point.
```console
$ go run . -f email -d 1 -u https://www.mandiant.com/report-incident

   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/                                                   

                projectdiscovery.io

[INF] Current katana version v1.1.0 (latest)
[INF] Started standard crawling for => https://www.mandiant.com/report-incident
investigations@mandiant.com
investigations@mandiant.com
```

**Comment by dogancanbakir** [comment] 2024-08-05 11:58
Closing this; works as expected.

**Closed by dogancanbakir** 2024-08-05 11:58 UTC
Labels: Type: Bug
