### ISSUE TITLE
crawl error

### ISSUE THREAD

**Issue by defaul0t** [projectdiscovery/katana#472] opened 2023-06-12 07:54 UTC
error info

nt/1.1\r\nAccept-Encoding: gzip\r\n\r\n"},"error":"[hybrid:RUNTIME] context deadline exceeded \u003c- could not get dom\n"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x101cc37]

goroutine 40658 [running]:
github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).navigateRequest(0xc0007185d0, 0xc00c10ecd0, 0xc007e2efa0)
        /home/runner/work/katana/katana/pkg/engine/hybrid/crawl.go:157 +0xc37
github.com/projectdiscovery/katana/pkg/engine/common.(*Shared).Do.func1()
        /home/runner/work/katana/katana/pkg/engine/common/base.go:226 +0xeb
created by github.com/projectdiscovery/katana/pkg/engine/common.(*Shared).Do
        /home/runner/work/katana/katana/pkg/engine/common/base.go:216 +0x2b

./katana -list scan.txt -headless -no-sandbox -jc -aff  -iqp -d 9 -kf robotstxt,sitemapxml  -nc  -json -o at.json

**Comment by MetzinAround** [comment] 2023-06-12 13:48
Could you show me the command you were running when the error occurred?

**Comment by MetzinAround** [comment] 2023-06-12 19:37
Oh wait, is it this? 
`./katana -list scan.txt -headless -no-sandbox -jc -aff -iqp -d 9 -kf robotstxt,sitemapxml -nc -json -o at.json`

**Comment by ehsandeep** [comment] 2023-06-12 22:50
Duplicate of https://github.com/projectdiscovery/katana/issues/380 and fixed in the latest release - https://github.com/projectdiscovery/katana/releases/tag/v1.0.2

**Closed by ehsandeep** 2023-06-12 22:50 UTC
Labels: Type: Bug
